apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - api.yaml
  - monitoring.yaml
  - network-policies.yaml
  - backup.yaml
  - logging.yaml

configMapGenerator:
  - name: loki-config
    namespace: task-manager
    files:
      - loki.yml=observability/loki.yml
  - name: alloy-config
    namespace: task-manager
    files:
      - config.alloy=alloy-config.alloy
  - name: grafana-datasources
    namespace: task-manager
    files:
      - datasources.yml=observability/grafana/provisioning/datasources/datasources.yml
  - name: grafana-dashboard-provider
    namespace: task-manager
    files:
      - dashboards.yml=observability/grafana/provisioning/dashboards/dashboards.yml
  - name: grafana-alerting
    namespace: task-manager
    files:
      - contact-points.yml=observability/grafana/provisioning/alerting/contact-points.yml
      - rules.yml=observability/grafana/provisioning/alerting/rules.yml
  - name: grafana-dashboards
    namespace: task-manager
    files:
      - task-api.json=observability/grafana/dashboards/task-api.json
      - operations-logs.json=observability/grafana/dashboards/operations-logs.json

generatorOptions:
  disableNameSuffixHash: true
